### ISSUE TITLE
Combine all the video processing tasks into a single task

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#102]
### Feature Description

_A clear and concise description of the feature you're requesting._

Reduce the pipeline computation time by combining all the tasks that require the video on the worker together.

### Use Case

_Please provide a use case to help us understand your request in context._

Drastically reducing the pipeline computation time.

### Solution

_Please describe your ideal solution._

Move the function calls to generate thumbnails to the start of the pipeline with the strip audio and generate hash.

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by Shak2000** [comment]
I am currently working on this issue.
