### ISSUE TITLE
Add basic instance metadata collection to infrastructure stack

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#117]
### Feature Description

_A clear and concise description of the feature you're requesting._

Partially discussed in https://github.com/CouncilDataProject/cdp-roadmap/issues/3, it would be nice to have a collection with a single document to pull metadata about the instance.

### Use Case

_Please provide a use case to help us understand your request in context._

Most importantly would be which cdp version the instance is currently on. This would help in determine which features the instance supports.

### Solution

_Please describe your ideal solution._

Use pulumi gcp firestore document resource to create / update the same document every time the infrastructure is upgraded.
https://www.pulumi.com/docs/reference/pkg/gcp/firestore/document/

@tohuynh @isaacna can you think of other metadata that would be good to store in the database itself about the instance?
version, some subset of cookiecutter params maybe? anything else?

**Comment by tohuynh** [comment]
Not sure how you would store this. But from a researcher's perspective querying across multiple instances I'd want to be able to determine what the database models and transcript models (maybe even ingestion models too) look like for each instance. It would be cool if from the metadata we could produce something like what we currently do for our [gh-pages](https://councildataproject.org/cdp-backend/transcript_model.html). Either store the generated gh-page links or actually store the model templates?

**Comment by JacksonMaxfield** [comment]
> Not sure how you would store this. But from a researcher's perspective querying across multiple instances I'd want to be able to determine what the database models and transcript models (maybe even ingestion models too) look like for each instance. It would be cool if from the metadata we could produce something like what we currently do for our [gh-pages](https://councildataproject.org/cdp-backend/transcript_model.html). Either store the generated gh-page links or actually store the model templates?

Wouldn't this information be implicitly contained in "version"? i.e. whatever version the instance is on has that versions db models. I mean. the shorthand would be "install cdp-backend=={VERSION STORED IN DB}" then run "create_cdp_database_uml".

Although, this is just an argument for us to move over to readthedocs instead of self publishing our docs. readthedocs stores all versions of doc pages so we could link straight to it that way.

**Comment by tohuynh** [comment]
Maybe I'm thinking too far into the future. I was thinking of the web API in https://github.com/CouncilDataProject/cdp-roadmap/issues/3, it would be nice to have an endpoint like `/transcript_models/seattle` or `/instances/seattle/transcript_model` to allow users to retrieve the transcript model without having to install a cdp-backend version. Or something else that would allow users to see a template of the data they are retrieving.

**Comment by JacksonMaxfield** [comment]
Agree. Even if it's lower it should be fine.

An interesting note is that if the pipeline is provided a closed caption file, we just assert that the confidence is 0.97 which is _questionable_. We somewhat pulled that number out of the air.

**Comment by isaacna** [comment]
Hm in that case, thoughts keeping it at 0.97 and only add to the average when we use transcription without provided captions?

**Comment by JacksonMaxfield** [comment]
> Hm in that case, thoughts keeping it at 0.97 and only add to the average when we use transcription without provided captions? But if that's too specific than I'm good just not including the average confidence stat in the metadata stack

Yea that's fair. I think it's decently easy to simply run a query and calculate it yourself if you're interested. So maybe we just don't include it unfortunately...

(Sidenote, I really do mean unfortunately, I thought _a lot_ about this over the last couple of days and I think it would be really interesting to see if there are regional differences in how confident Google's model is. I.e. Pacific northwest cities / transcripts vs east coast cities / transcripts.)

**Comment by JacksonMaxfield** [comment]
So after a bit, I think for now the basic metadata should be:

* current cdp backend version
* municipality name
* hosting_github_url
* firestore_region
* municipality type (city council, school board, etc.) -- default to city council
