### ISSUE TITLE
Debug why some files can't be archived / linked

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-backend#119]
### Describe the Bug

_A clear and concise description of the bug._

Was checking the logs of test-deployment and saw that some files fail to be archived: https://github.com/CouncilDataProject/test-deployment/runs/3776409036?check_suite_focus=true#step:8:118

I can click on that link and it is a real file that is publically accessibile.

### Expected Behavior

_What did you expect to happen instead?_

All publically accessible files are archivable.

**Comment by JacksonMaxfield** [comment]
@isaacna I think this may also be timeout errors or similar: https://github.com/intake/filesystem_spec/issues/619#issuecomment-825029746

I am seeing a lot of failures on seattle-staging backfill runs because of timeout errors: https://github.com/CouncilDataProject/seattle-staging/runs/3875382085?check_suite_focus=true#step:9:157

**Comment by isaacna** [comment]
Aren' the timeout errors what'

> It honestly may be just that we are storing that file and then _instantly_ checking if it exists. I think most storage systems are "eventually consistent" / it may take some time for Google to properly hit the result after storing. (Especially when we are uploading hundreds of files at a time...)

I'm kinda confused about this, but for this specific case isn't it checking that the remote resource `https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf` exists via an http request? Or am I misunderstanding what `fsspec.url_to_fs` does? 

I was thinking that sometimes there's just an error while making the http request (for the non google uri's): https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/http.py#L305-L315

Also for the timeout errors during `resource_copy` I dont' think that's related to the validator issue but still a problem. Maybe we could add some retry logic into `resource_copy`?

**Comment by isaacna** [comment]
I also created a script that just checks creates a file store using `fsspec`, and checks whether the resource exists. I ran it in a loop but haven't seen a case with the resource suddenly not being found. Maybe the github action runner is just more prone to http errors or timeouts?

**Comment by isaacna** [comment]
It looks like Event gather runs 160-164 (the ones since bumping the cdp-backend version) haven't encountered the `could not be archived` issue. I'll wait for a few more runs before saying that the HEAD request fixed the issue, but fingers crossed that it did

**Comment by isaacna** [comment]
> I know. I have been digging through the code as well and the `AsyncFileSystem` is hard to navigate. I was able to reproduce the timeout error on my local machine so I can try to debug it as well.

Sounds good, there's probably some simple way to increase the timeout but it isn't obvious based on the docs or code. It may be worth trying to clone `fsspec` and mess around with it directly 

> I will say, this issue and #120 combined are the primary reasons for the v3 pipeline to fail. More on #120 in it's issue comments.

Yeah I think fixing these should be a priority, but at least the issue #120 seems to have a fairly straightforward solution

**Comment by isaacna** [comment]
> fsspec + that weird HTTP options dict a try

Which HTTP options are you referring to?
