### ISSUE TITLE
Store files to unique paths instead of filenames

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#120]
### Feature Description

_A clear and concise description of the feature you're requesting._

For certain files that we want to archive (such as person picture) we are simply downloading and then uploading to our own file storage and storing at `/[filename]`. Instead let's store the file at a unique path so that we can maybe reduce the amount of uploads.

### Use Case

_Please provide a use case to help us understand your request in context._

In addition to reducing the number of uploads we run, this should also just speed up the pipeline, and crucially: make our data storage "safer", in the case that a person uses the same filenaming for all of their pictures i.e. `council.gov/{PERSONNAME}/picture.png` the current pipeline would result in only storing a single picture for them all instead of storing them uniquely.

### Solution

_Please describe your ideal solution._

Anytime we are using the `download` -> `upload` pattern: https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/pipeline/event_gather_pipeline.py#L874

change it to `download` -> `hash` -> `check if exists (by hash)` -> `(optional) upload (with hash as the file name)`.

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by Shak2000** [comment]
Hi. I am interested in working on this issue.
