### ISSUE TITLE
Set public read during CDPStack creation

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-backend#14]
## Use Case
*Please provide a use case to help us understand your request in context*

Maybe this should be a parameter in the CDPStack object but currently our standard for infrastructure is to allow public read so during stack creation, we should set the default read permissions for the bucket and database to be public as well.

I say potentially a parameter because dev stacks don't need to be public read which could save money for the dev :upside_down_face: 

(the dev stack with example data should really only cost like $0.01 though since the example data should be really minimal)

## Solution
*Please describe your ideal solution*

I haven't figured out which Pulumi resource is needed (or really if it is possible to do with the pulumi API, it may need to be a second `ComponentResource` that calls out to `gcloud` in a subprocess)

But setting this and managing permissions through code would be incredibly useful.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by JacksonMaxfield** [comment]
Seems like we can use the [Firestore CLI](https://cloud.google.com/firestore/docs/security/get-started#use_the_firebase_cli) to do this. So either a post-script thing _or_ writing our own `ComponentResource` to do subprocess it out to the CLI

**Comment by JacksonMaxfield** [comment]
This is now possible with the Pulumi 3.0 Google Native Provider:

https://www.pulumi.com/docs/reference/pkg/google-native/firebaserules/v1/ruleset/

I attempted it but it is finicky and tricky to get right / I may have been doing something incorrectly. Going to hold off until needed for research queries.

**Comment by JacksonMaxfield** [comment]
Firestore public read rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read: if request.auth == null;
    }
  }
}
```

Firebase storage public read rules:
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read;
    }
  }
}
```

**Comment by JacksonMaxfield** [comment]
Looks like the process for this will be:

1. create the rulesets with: https://www.pulumi.com/docs/reference/pkg/google-native/firebaserules/v1/ruleset/
2. use the rulesets in https://www.pulumi.com/docs/reference/pkg/google-native/firebaserules/v1/release/

**Comment by JacksonMaxfield** [comment]
Got it working! :tada:

I ditched trying to get Pulumi ruleset working and went with a simple node script

**Comment by JacksonMaxfield** [comment]
Alright. I _thought_ I had it working but when doing thorough testing, I saw that was failing to initialize the Firestore Security Rules.

Everything runs through just fine, all resources are technically created but Firestore Security Rules aren't being _applied_. They will only apply after visiting the Firestore Security Rules Web UI and _then_ rerunning the set-public-read script. In some cases, I get an "entity does not exist" error.

I opened a ticket with Firebase Support so hopefully I will hear back soon.

**Comment by JacksonMaxfield** [comment]
Tracking with Firebase support and https://github.com/pulumi/pulumi-google-native/issues/196

**Comment by JacksonMaxfield** [comment]
Also needs a CORS rule: https://firebase.google.com/docs/storage/web/download-files#download_data_via_url

**Comment by JacksonMaxfield** [comment]
Parts of this (specifically the CORS) may be able to be completed with a Dynamic Provider: https://www.pulumi.com/blog/dynamic-providers/
