### ISSUE TITLE
Add a function for replacing all http URIs with https URIs when possible

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#148]
We already do this for session video URIs: https://github.com/CouncilDataProject/cdp-backend/blob/294254928cfc9ff1861d60f2208c91dd533b15e6/cdp_backend/pipeline/event_gather_pipeline.py#L337

However this should be the default standard whenever we check an HTTP like URI.

If given an http(s) uri, try the uri in https first, then try it in http, whichever works, use it.

**Comment by isaacna** [comment]
Once we have this function, did you just want to call it whenever a URI is involved? It may be more convenient to add the function on all the fields that are a uri in the ingestion/db model classes. 

With `@dataclass` and the FireO models we could do something like [this](https://stackoverflow.com/questions/60179799/python-dataclass-whats-a-pythonic-way-to-validate-initialization-arguments)?
