### ISSUE TITLE
ASV for tracking our SR model configuration and performance

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-backend#152]
With #150, we should come up with a more robust system for tracking how well our speech recognition model performs. Both our google configuration, or, if we ever train our own model or switch services, simply a method for checking with model is currently performing best.

I have previously set up [ASV](https://asv.readthedocs.io/en/stable/) for aicsimageio to track our [IO perf per each commit](https://allencellmodeling.github.io/aicsimageio/_benchmarks/index.html#/) and I think I could setup something up for this as well.

Unlike AICSImageIO's ASV setup which runs on every commit, I think I would only set it up to run / update on every tag / new release to reduce cost.

As for dataset, I think I will try to find 5 meetings of seattle city council that have transcripts converted from closed caption files, and store those transcript JSONs in the repo / library to use as "ground truth". While the closed caption files aren't 100% correct, they are very close to it, and crutially, they are creating by a government employee as a part of the meeting process and used on government websites so it's really asking the question: "does the SR model configuration perform close to manual closed caption file creation"

Finally as for metric, the general idea in my head is to process each of the transcripts with the model and then use [word error rate](https://pypi.org/project/jiwer/) to see how the model performs against the ground truth closed caption converted file.

cc @nniiicc

**Comment by JacksonMaxfield** [comment]
Realizing something cool here.... @nniiicc could we get an undergrad on this for research?

In addition to word error rate, this is a place where we can see _which_ words google gets wrong and what they replace it with. I.e. during land acknowledgements, with non-anglo-saxon names, etc. what words does the model choose in place?

This basically could be used as the starting point for the paper we talked about with Iisaaksiichaa and Mandy.

**Comment by nniiicc** [comment]
Yes! 

@JacksonMaxfield can you add this to Friday agenda so we can scope
