### ISSUE TITLE
Remove `is_required` from `create_constant_value_validator` 

### ISSUE THREAD

**Issue by isaacna** [CouncilDataProject/cdp-backend#160]
### Feature Description

As discussed in #155 

We don't need `is_required` in the function `create_constant_value_validator`. We can just use the `required` arg that is built in for all FireO fields. We should just remove the param in `create_constant_value_validator` and adjust the usages to keep things consistent

**Comment by dphoria** [comment]
:sweat_smile: Thanks for creating this Isaac. I came to do so cursing at myself for not having done it earlier. :pray:

**Comment by isaacna** [comment]
No worries! Just put out a PR for it
