### ISSUE TITLE
Add a function for downloading youtube videos

### ISSUE THREAD

**Issue by isaacna** [CouncilDataProject/cdp-backend#161]
### Feature Description

[Context](https://github.com/CouncilDataProject/cdp-scrapers/pull/72)

Add a function for downloading youtube videos

### Use Case

Some deployments (such as portland) may upload their videos via youtube. We need to be able to download the video for both audio stripping for session hash generation, trasncription, and speaker classification

### Solution

We can use [youtube-dl](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#embedding-youtube-dl)

**Comment by Shak2000** [comment]
@isaacna I would be happy to help you with this task.

**Comment by isaacna** [comment]
@Shak2000 Sure all yours

**Comment by Shak2000** [comment]
I tried `youtube-dl`, but it's very slow (about 50 kps). I found [this post](https://github.com/ytdl-org/youtube-dl/issues/30102) saying that `yt-dlp` is much faster, and I'll try it soon.

**Comment by isaacna** [comment]
> I tried `youtube-dl`, but it's very slow (about 50 kps). I found [this post](https://github.com/ytdl-org/youtube-dl/issues/30102) saying that `yt-dlp` is much faster, and I'll try it soon.

Sounds good, I totally support using `yt-dlp` since it seems like a well supported fork
