### ISSUE TITLE
WebVTT parsing fails for Boston

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#190]
### Describe the Bug

_A clear and concise description of the bug._

WebVTT parsing isn't the greatest for Boston:
https://councildataproject.org/boston/#/events/3c7f0df0ecd4

### Expected Behavior

_What did you expect to happen instead?_

WebVTT parsing should be the same level or better than Seattle

**Comment by JacksonMaxfield** [comment]
Boston event gather log for where closed caption is pulled from: https://github.com/CouncilDataProject/boston/runs/6759035563?check_suite_focus=true#step:9:7200

**Comment by JacksonMaxfield** [comment]
@isaacna or @Shak2000 do either of you have the time or interest to take this one?

**Comment by isaacna** [comment]
> @isaacna or @Shak2000 do either of you have the time or interest to take this one?

I should have some time later this week or next to take a look
