### ISSUE TITLE
Process vimeo video URLs

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-backend#191]
### Feature Description

_A clear and concise description of the feature you're requesting._

Download and process videos hosted by vimeo.

### Use Case

_Please provide a use case to help us understand your request in context._

Certain munis store videos and captions on Vimeo (chicago: https://vimeo.com/showcase/citycouncil)

### Solution

_Please describe your ideal solution._

Likely a solution similar to the implementation of m3u8 processing: https://github.com/CouncilDataProject/cdp-backend/pull/188

There is a vimeo downloader python library: https://github.com/yashrathi-git/vimeo_downloader so we can use that for now but we should also make a PR to that library to add functionality to download the captions as well.

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by Shak2000** [comment]
Hi! I would like to work on this issue.

**Comment by JacksonMaxfield** [comment]
Thanks Shak!

**Comment by Shak2000** [comment]
I currently working with the Vimeo Downloader. Up until now, I found a few city councils active on Vimeo for which the Vimeo Downloader works and a few city councils for which the Downloader does not work.

For example, the Downloader works for:

- [Versailles, Kentucky](https://vimeo.com/channels/cityofversailles) (e.g., [this video](https://vimeo.com/723814841))
- [Norwood Young America, Minnesota](https://vimeo.com/user6038697) (e.g., [this](https://vimeo.com/720726821) [video](https://vimeo.com/200855463))

On the other hand, the Downloader does NOT work for:

- [Chicago, Illinois](https://vimeo.com/showcase/citycouncil) (e.g., [this](https://vimeo.com/722690793) [video](https://vimeo.com/showcase/6277394/video/722690793))
- Rockville, Minnesota (e.g., [this video](https://vimeo.com/686512896))

**Comment by Shak2000** [comment]
I have code ready for the city councils for which the Vimeo Downloader does work. Should I push them to GitHub right now?

In addition, do you think that it is okay to submit an issue to the Vimeo Downloader GitHub repository?

**Comment by Shak2000** [comment]
I think that I found the difference between the city council videos where the Vimeo Downloader does and does not work. I found out the Downloader only works when the file delivered includes the following:
`"progressive":[{"profile":"164","width":474,"mime":"video/mp4","fps":29,"url":"https://vod-progressive.akamaized.net/exp=1657520070~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4145%2F28%2F720726821%2F3342874040.mp4~hmac=e620725bd0cf503b1837a3e05e285528d0cc917146a5be6c23f581b1cfe30f6b/vimeo-prod-skyfire-std-us/01/4145/28/720726821/3342874040.mp4","cdn":"akamai_interconnect","quality":"360p","id":"194885ae-83b7-4580-ad4c-6f7fbec33b7b","origin":"gcs","height":360}`

For the videos where the Downloader does not succeed, the server returns a file that includes the following:
`"progressive":[]`

**Comment by Shak2000** [comment]
Thanks @nniiicc and @JacksonMaxfield!

How do you know that the video for Chicago is set to private?

**Comment by evamaxfield** [comment]
I actually don't know if would be described as "private"? @nniiicc wouldn't a private video be hidden? To me this reads as "downloadable=False" or something.

The way we "know" that is simply that there isn't a download button anywhere and the multiple Vimeo downloaders we have tried and looked at don't work haha

**Comment by Shak2000** [comment]
@evamaxfield Thanks for the clarification!

**Comment by Shak2000** [comment]
The PR is now ready for review.

**Comment by Shak2000** [comment]
@evamaxfield After I changed `file_utils` to return `f"{dst}/{dst.name}.mp4"`, the `assert` line in `test_file_utils` failed for Windows due to the `(EXAMPLE_VIMEO, Path("503166067") / "503166067.mp4")` in `test_file_utils`. In Windows, one of the two code paths returns a Path with a `\`, and the other returns a Path with a `/`. I don't have a Windows machine to debug my code.

**Comment by evamaxfield** [comment]
Reopening as we further investigate the private / non-downloadable vimeo links

**Comment by sagarrat7** [comment]
I would like to work on non-downloadable vimeo links! I'm currently investigating this right now and I plan to open a PR.

**Comment by evamaxfield** [comment]
Thanks so much @sagarrat7 !!

**Comment by sagarrat7** [comment]
No problem!

**Comment by italo13d** [comment]
Any update on this?

**Comment by evamaxfield** [comment]
@italo13d I believe this was released already. Are you experiencing errors?
