### ISSUE TITLE
Fix deadlink in event gather pipeline docs that links to event ingestion data model

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#41]
Broken link in docs: https://councildataproject.github.io/cdp-backend/event_gather_pipeline.html

Should be updated to the renamed Event Ingestion Data Model

**Comment by tohuynh** [comment]
The generated link is `https://councildataproject.github.io/cdp-backend/cdp-backend/event_data_ingestion_model.html`

I think just need to remove extra cdp-backend

**Comment by JacksonMaxfield** [comment]
Seems like it. I can also handle this if you want. I am planning on making a PR later today to do a bunch of function name + documentation cleanup and moving some functions around
