### ISSUE TITLE
Event Gather Pipeline: Move database uploads to after pipeline processing

### ISSUE THREAD

**Issue by isaacna** [CouncilDataProject/cdp-backend#50]
## Use Case
It would be nice to handle db uploads in the event gather pipeline to after all the processing logic (audio creation, transcript creation, etc.) so that any errors can get surfaced before uploading to the database.

## Solution
This can be done storing the results of processing in a temporary container then doing all the database calls with the results of the processing

**Comment by JacksonMaxfield** [comment]
I think this is done with #69
