### ISSUE TITLE
Add back `resource_exists` validator for `uri` field on File

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#52]
We had to remove the usage of `resources_exists` from the uri field validator because we couldn't think of a method to pass the google credentials to the validator. At some point we may want to add this back but this shouldn't hold up #49 from being merged.

> Actually after trying this, I think passing another param to the validator is a little tricky. 

> I can add kwargs to `resource_exists`, but I'm not sure if there's an easy way to pass in `fs` into that function inside `uri = fields.TextField(required=True, validator=validators.resource_exists)`. 

> Because model fields in FireO are assigned like `db_file.uri = "gs://stuff"`, I'm not sure we can pass in other params into the `validators` arg. 

> Would it make more sense to just validate separately outside of FireO's built-in field validation? Or is there an easier way to do this I'm missing?

_Originally posted by @isaacna in https://github.com/CouncilDataProject/cdp-backend/pull/49#discussion_r589185839_

**Comment by isaacna** [comment]
Based on [FireO's implementation](https://github.com/octabytes/FireO/blob/master/src/fireo/fields/field_attribute.py#L87-L95), I don't think it's possible to pass in kwargs to a validator method passed in. 

Two things we could do are:
1. Make a PR to FireO to support extra validator args 
2. Handle validation on database models on our own. We could do something like create an abstract base class with a `validator` field that takes in a callable, and a `validator_args` field. Then we can have each database model we have also inherit from that class.

I think 2 would be the easier option.
