### ISSUE TITLE
Add ability to run tests after install to verify

### ISSUE THREAD

**Issue by rkiddy** [CouncilDataProject/cdp-backend#63]
I have looked for a "runTest" target in the Makefile. I can see that tests exist. I just cannot see if any other setup is required before the tests can be run.

I will add a PR for any Makefile or documentation change that I discover is needed.

**Comment by JacksonMaxfield** [comment]
Hey @rkiddy, if you are talking about the pure unit tests, `make build` will run the whole test suite against multiple python versions. It is just a shorthand for `tox` which is a python library to manage testing environments and runners. So if you just want to run tests on Py39 you can run `tox -e py39` or if you just want to run lint, formatting, and type checks you can do `tox -e lint`

`tox -e {test-environment}`

You can clean up these unit test environments with `make clean`

If you are trying to run end-to-end pipeline tests, we have some dev infrastructure commands to get setup and some make commands to run "minimal event ingestion" and "random event ingestion"

1. [rand event ingestion](https://github.com/CouncilDataProject/cdp-backend/blob/main/Makefile#L76)
2. [minimal event ingestion](https://github.com/CouncilDataProject/cdp-backend/blob/main/Makefile#L81)
3. [dev environment / stack setup](https://github.com/CouncilDataProject/cdp-backend/tree/main/dev-infrastructure)

**Comment by JacksonMaxfield** [comment]
In general, the [CONTRIBUTING](https://github.com/CouncilDataProject/cdp-backend/blob/main/CONTRIBUTING.md) doc has the info on unit testing stuff.

**Comment by JacksonMaxfield** [comment]
Closing. I think our Contributing docs are pretty good... If you are still having trouble with this please just let me know. Happy to talk and PR to fix anything.
