### ISSUE TITLE
Optimize stored thumbnails for web render

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-backend#84]
### Feature Description

_A clear and concise description of the feature you're requesting._

Downscale and compress images to preemptively help speed up our webpage rendering times.

### Use Case

_Please provide a use case to help us understand your request in context._

Specifically I am worried about the event search results / the general events filtering and query page due to trying to render ~10 events with all their thumbnails at the same time.

### Solution

_Please describe your ideal solution._

* if the image is larger than 960 x 540 downscale images and gif to 960 x 540
* change the format for the static thumbnail from png to webp

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by JacksonMaxfield** [comment]
@Shak2000 can you comment on this issue and I will assign it to you

**Comment by Shak2000** [comment]
I have successfully managed to extract and use information on image sizes. I have also started working on this issue.
